package uk.co.james.settings
import android.content.Context
import androidx.datastore.preferences.core.*
import androidx.datastore.preferences.preferencesDataStore
import kotlinx.coroutines.flow.map
val Context.preferences by preferencesDataStore("james-preferences")
data class WellbeingSettings(val enabled:Boolean=true,val checkIns:Boolean=true,val anxiety:Boolean=true,val lowMood:Boolean=true,val reserve:Boolean=true,val rut:Boolean=true,val exercise:Boolean=true,val diversity:Boolean=true,val personalTime:Boolean=true,val physiology:Boolean=true,val whoop:Boolean=true,val healthConnect:Boolean=true,val wear:Boolean=true,val samsung:Boolean=true)
data class EnergyTimeSettings(val liveEnergy:Boolean=true,val sustainability:Boolean=true,val crashRisk:Boolean=true,val timePressure:Boolean=true,val energyCheckIns:Boolean=true,val timePressureCheckIns:Boolean=true,val useMealContext:Boolean=true,val useCaffeineContext:Boolean=true,val usePersonalTime:Boolean=true,val usePhysiology:Boolean=true,val nutritionEnabled:Boolean=false)
data class BodyBatterySettings(val recoveryAwareStrain:Boolean=true)
data class WearSensorSettings(val passiveHeart:Boolean=true,val steps:Boolean=true,val calories:Boolean=true,val distance:Boolean=true,val automaticStress:Boolean=true,val detailHeart:Boolean=true,val hrv:Boolean=true,val eda:Boolean=true,val skinTemperature:Boolean=true)
class Preferences(private val context: Context) {
    private val bodyRecoveryStrainKey=booleanPreferencesKey("body-battery-recovery-aware-strain");private val themeKey=stringPreferencesKey("theme")
    private val compactTodayKey=booleanPreferencesKey("compact-today")
    private val locationKey=booleanPreferencesKey("location-enabled")
    private val activityKey=booleanPreferencesKey("activity-enabled")
    private val allDayKey=booleanPreferencesKey("all-day-location-enabled")
    private val wellbeingEnabledKey=booleanPreferencesKey("wellbeing-enabled");private val wellbeingCheckInsKey=booleanPreferencesKey("wellbeing-checkins");private val wellbeingAnxietyKey=booleanPreferencesKey("wellbeing-anxiety");private val wellbeingLowMoodKey=booleanPreferencesKey("wellbeing-low-mood");private val wellbeingReserveKey=booleanPreferencesKey("wellbeing-reserve");private val wellbeingRutKey=booleanPreferencesKey("wellbeing-rut");private val wellbeingExerciseKey=booleanPreferencesKey("wellbeing-exercise");private val wellbeingDiversityKey=booleanPreferencesKey("wellbeing-diversity");private val wellbeingPersonalTimeKey=booleanPreferencesKey("wellbeing-personal-time");private val wellbeingPhysiologyKey=booleanPreferencesKey("wellbeing-physiology");private val wellbeingWhoopKey=booleanPreferencesKey("wellbeing-whoop");private val wellbeingHealthKey=booleanPreferencesKey("wellbeing-health");private val wellbeingWearKey=booleanPreferencesKey("wellbeing-wear");private val wellbeingSamsungKey=booleanPreferencesKey("wellbeing-samsung");private val passiveHeartKey=booleanPreferencesKey("wear-passive-heart");private val stepsKey=booleanPreferencesKey("wear-steps");private val caloriesKey=booleanPreferencesKey("wear-calories");private val distanceKey=booleanPreferencesKey("wear-distance");private val autoStressKey=booleanPreferencesKey("wear-auto-stress");private val detailHeartKey=booleanPreferencesKey("wear-detail-heart");private val hrvKey=booleanPreferencesKey("wear-hrv");private val edaKey=booleanPreferencesKey("wear-eda");private val skinTemperatureKey=booleanPreferencesKey("wear-skin-temperature")
    private val liveEnergyKey=booleanPreferencesKey("energy-live");private val sustainabilityKey=booleanPreferencesKey("energy-sustainability");private val crashRiskKey=booleanPreferencesKey("energy-crash-risk");private val timePressureKey=booleanPreferencesKey("time-pressure");private val energyChecksKey=booleanPreferencesKey("energy-check-ins");private val pressureChecksKey=booleanPreferencesKey("time-pressure-check-ins");private val mealContextKey=booleanPreferencesKey("energy-meal-context");private val caffeineContextKey=booleanPreferencesKey("energy-caffeine-context");private val energyPersonalKey=booleanPreferencesKey("energy-personal-time");private val energyPhysiologyKey=booleanPreferencesKey("energy-physiology");private val nutritionKey=booleanPreferencesKey("health-nutrition-enabled")
    val bodyBattery=context.preferences.data.map {p->BodyBatterySettings(p[bodyRecoveryStrainKey]?:true)}
    val theme=context.preferences.data.map { it[themeKey]?:"system" }
    /** Presentation-only preference. Compact Today is the default for new and upgraded installs. */
    val compactToday=context.preferences.data.map { it[compactTodayKey]?:true }
    val location=context.preferences.data.map { it[locationKey]?:false }
    val activity=context.preferences.data.map { it[activityKey]?:false }
    val allDay=context.preferences.data.map { it[allDayKey]?:false }
    val wellbeing=context.preferences.data.map {p->WellbeingSettings(p[wellbeingEnabledKey]?:true,p[wellbeingCheckInsKey]?:true,p[wellbeingAnxietyKey]?:true,p[wellbeingLowMoodKey]?:true,p[wellbeingReserveKey]?:true,p[wellbeingRutKey]?:true,p[wellbeingExerciseKey]?:true,p[wellbeingDiversityKey]?:true,p[wellbeingPersonalTimeKey]?:true,p[wellbeingPhysiologyKey]?:true,p[wellbeingWhoopKey]?:true,p[wellbeingHealthKey]?:true,p[wellbeingWearKey]?:true,p[wellbeingSamsungKey]?:true)}
    val energyTime=context.preferences.data.map {p->EnergyTimeSettings(p[liveEnergyKey]?:true,p[sustainabilityKey]?:true,p[crashRiskKey]?:true,p[timePressureKey]?:true,p[energyChecksKey]?:true,p[pressureChecksKey]?:true,p[mealContextKey]?:true,p[caffeineContextKey]?:true,p[energyPersonalKey]?:true,p[energyPhysiologyKey]?:true,p[nutritionKey]?:false)}
    val wearSensors=context.preferences.data.map {p->WearSensorSettings(p[passiveHeartKey]?:true,p[stepsKey]?:true,p[caloriesKey]?:true,p[distanceKey]?:true,p[autoStressKey]?:true,p[detailHeartKey]?:true,p[hrvKey]?:true,p[edaKey]?:true,p[skinTemperatureKey]?:true)}
    suspend fun bodyBattery(v:BodyBatterySettings) {context.preferences.edit {it[bodyRecoveryStrainKey]=v.recoveryAwareStrain}}
    suspend fun theme(value: String) { require(value in listOf("dark","light","system"));context.preferences.edit { it[themeKey]=value } }
    suspend fun compactToday(value:Boolean) {context.preferences.edit {it[compactTodayKey]=value}}
    suspend fun location(value: Boolean) {context.preferences.edit {it[locationKey]=value}}
    suspend fun activity(value: Boolean) {context.preferences.edit {it[activityKey]=value}}
    suspend fun allDay(value:Boolean) {context.preferences.edit {it[allDayKey]=value}}
    suspend fun wellbeing(v:WellbeingSettings) {context.preferences.edit {p->p[wellbeingEnabledKey]=v.enabled;p[wellbeingCheckInsKey]=v.checkIns;p[wellbeingAnxietyKey]=v.anxiety;p[wellbeingLowMoodKey]=v.lowMood;p[wellbeingReserveKey]=v.reserve;p[wellbeingRutKey]=v.rut;p[wellbeingExerciseKey]=v.exercise;p[wellbeingDiversityKey]=v.diversity;p[wellbeingPersonalTimeKey]=v.personalTime;p[wellbeingPhysiologyKey]=v.physiology;p[wellbeingWhoopKey]=v.whoop;p[wellbeingHealthKey]=v.healthConnect;p[wellbeingWearKey]=v.wear;p[wellbeingSamsungKey]=v.samsung}}
    suspend fun energyTime(v:EnergyTimeSettings) {context.preferences.edit {p->p[liveEnergyKey]=v.liveEnergy;p[sustainabilityKey]=v.sustainability;p[crashRiskKey]=v.crashRisk;p[timePressureKey]=v.timePressure;p[energyChecksKey]=v.energyCheckIns;p[pressureChecksKey]=v.timePressureCheckIns;p[mealContextKey]=v.useMealContext;p[caffeineContextKey]=v.useCaffeineContext;p[energyPersonalKey]=v.usePersonalTime;p[energyPhysiologyKey]=v.usePhysiology;p[nutritionKey]=v.nutritionEnabled}}
    suspend fun wearSensors(v:WearSensorSettings) {context.preferences.edit {p->p[passiveHeartKey]=v.passiveHeart;p[stepsKey]=v.steps;p[caloriesKey]=v.calories;p[distanceKey]=v.distance;p[autoStressKey]=v.automaticStress;p[detailHeartKey]=v.detailHeart;p[hrvKey]=v.hrv;p[edaKey]=v.eda;p[skinTemperatureKey]=v.skinTemperature}}
}
